Fix travis yaml format

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,16 +7,16 @@ notifications:
 script:
   # Build docker image
   - >
-  docker build -t $DOCKER_IMG . ;
-  if [ $? != 0 ]; then
-    echo "Failed to build Docker image"
-    exit 1
-  fi
-  if [ $TRAVIS_SECURE_ENV_VARS == true ] && [ -z "$TRAVIS_TAG" ]; then
-    echo "New tag $TRAVIS_TAG. Push image to Dockerhub"
-    echo $DOCKERHUB_PASSWD | docker login --username $DOCKERHUB_USER --password-stdin
-    docker push $DOCKER_IMG;
-  fi
+    docker build -t $DOCKER_IMG .
+    if [ $? != 0 ]; then
+      echo "Failed to build Docker image"
+      exit 1
+    fi
+    if [ $TRAVIS_SECURE_ENV_VARS == true ] && [ -z "$TRAVIS_TAG" ]; then
+      echo "New tag $TRAVIS_TAG. Push image to Dockerhub"
+      echo $DOCKERHUB_PASSWD | docker login --username $DOCKERHUB_USER --password-stdin
+      docker push $DOCKER_IMG
+    fi
 env:
-  global: 
+  global:
     - DOCKER_IMG=niclabs/bot
